In [1]:
#numpy
import numpy as np

In [2]:
a = np.array([1,2,3,4])

In [3]:
a + a

array([2, 4, 6, 8])

In [4]:
[1,2] + [2,3]

[1, 2, 2, 3]

In [5]:
a = np.array([1,2,3,4], ndmin=3)

In [6]:
a

array([[[1, 2, 3, 4]]])

In [7]:
a

array([[[1, 2, 3, 4]]])

In [13]:
x=np.array([[1, 2, 3, 4],[1, 2, 3, 4]])

In [14]:
x.shape

(2, 4)

In [17]:
a = np.array([1,2,3,4])
a.reshape(2,1)

ValueError: cannot reshape array of size 4 into shape (2,1)

In [18]:
import pandas as pd

In [20]:
df=pd.read_csv("C:\\Users\\Administrator\\Downloads\\iris.csv")

In [23]:
df.head(7)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa

In [24]:
y = df[]

SyntaxError: invalid syntax (<ipython-input-24-217ef81019bb>, line 1)

In [25]:
y= df["species"]

In [31]:
x=df.drop("species",axis=1)
x

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
5             5.4          3.9           1.7          0.4
6             4.6          3.4           1.4          0.3
7             5.0          3.4           1.5          0.2
8             4.4          2.9           1.4          0.2
9             4.9          3.1           1.5          0.1
10            5.4          3.7           1.5          0.2
11            4.8          3.4           1.6          0.2
12            4.8          3.0           1.4          0.1
13            4.3          3.0           1.1          0.1
14            5.8          4.0           1.2          0.2
15            5.7          4.4           1.5          0.4
16            5.4          3.9           1.3          0.4
17            5.1          3.5           1.4          0.3
18            5.7          3.8           1.7          0.3
19            5.1          3.8           1.5          0.3
20            5.4          3.4           1.7          0.2
21            5.1          3.7           1.5          0.4
22            4.6          3.6           1.0          0.2
23            5.1          3.3           1.7          0.5
24            4.8          3.4           1.9          0.2
25            5.0          3.0           1.6          0.2
26            5.0          3.4           1.6          0.4
27            5.2          3.5           1.5          0.2
28            5.2          3.4           1.4          0.2
29            4.7          3.2           1.6          0.2
..            ...          ...           ...          ...
120           6.9          3.2           5.7          2.3
121           5.6          2.8           4.9          2.0
122           7.7          2.8           6.7          2.0
123           6.3          2.7           4.9          1.8
124           6.7          3.3           5.7          2.1
125           7.2          3.2           6.0          1.8
126           6.2          2.8           4.8          1.8
127           6.1          3.0           4.9          1.8
128           6.4          2.8           5.6          2.1
129           7.2          3.0           5.8          1.6
130           7.4          2.8           6.1          1.9
131           7.9          3.8           6.4          2.0
132           6.4          2.8           5.6          2.2
133           6.3          2.8           5.1          1.5
134           6.1          2.6           5.6          1.4
135           7.7          3.0           6.1          2.3
136           6.3          3.4           5.6          2.4
137           6.4          3.1           5.5          1.8
138           6.0          3.0           4.8          1.8
139           6.9          3.1           5.4          2.1
140           6.7          3.1           5.6          2.4
141           6.9          3.1           5.1          2.3
142           5.8          2.7           5.1          1.9
143           6.8          3.2           5.9          2.3
144           6.7          3.3           5.7          2.5
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [34]:
y_train

96     versicolor
105     virginica
66     versicolor
0          setosa
122     virginica
67     versicolor
28         setosa
40         setosa
44         setosa
60     versicolor
123     virginica
24         setosa
25         setosa
23         setosa
94     versicolor
39         setosa
95     versicolor
117     virginica
47         setosa
97     versicolor
113     virginica
33         setosa
138     virginica
101     virginica
62     versicolor
84     versicolor
148     virginica
53     versicolor
5          setosa
93     versicolor
          ...    
91     versicolor
41         setosa
58     versicolor
90     versicolor
48         setosa
88     versicolor
107     virginica
124     virginica
21         setosa
57     versicolor
144     virginica
129     virginica
37         setosa
140     virginica
1          setosa
52     versicolor
130     virginica
103     virginica
99     versicolor
116     virginica
87     versicolor
74     versicolor
121     virginica
149     virginica
20        

In [37]:
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing

In [45]:
le = preprocessing.LabelEncoder()
le.fit(y_train)
c = le.transform(y_train)

In [44]:
le.inverse_transform([1,2,0])

array(['versicolor', 'virginica', 'setosa'], dtype=object)

In [46]:
clf = LinearRegression()

In [51]:
clf.fit(X_train,c)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [52]:
clf.predict(X_test)

array([ 1.20820975, -0.03665373,  2.24352164,  1.34253376,  1.2976478 ,
        0.03392786,  1.05591015,  1.86801205,  1.3847852 ,  1.06346065,
        1.71054753, -0.08992765, -0.14459044, -0.08357461, -0.03612226,
        1.39118357,  1.99922887,  1.03489883,  1.25359311,  1.97914088,
        0.00453985,  1.59337385,  0.08533547,  1.91952518,  1.8427704 ,
        1.91280088,  1.78672743,  2.04228877,  0.02930375,  0.00530298,
       -0.15193827, -0.0696682 ,  1.19307467, -0.01913213, -0.03895438,
        1.7008309 ,  1.28857104, -0.07868476, -0.09394597, -0.18717068,
        1.74333034,  1.36142429,  1.31833032, -0.05055727, -0.10973865,
        0.9470501 ,  1.45981297,  1.69436299,  1.20860161,  2.14317237])

In [53]:
d=le.transform(y_test)
accuracy=clf.score(X_test,d)

In [54]:
print("Accuracy is {}",format(accuracy))

Accuracy is {} 0.9386052232801804


In [ ]:
lr= Logis